# Generated by Django 6.0.4 on 2026-07-14 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0013_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerinatalTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('patient_data', models.JSONField(help_text='Dados SINASC da gestante/recém-nascido.')),
                ('risk_score', models.FloatField(blank=True, help_text='Score de risco perinatal (0 a 1).', null=True)),
                ('risk_classification', models.CharField(blank=True, help_text='Classificação: BAIXO, MODERADO, ALTO.', max_length=20, null=True)),
                ('shap_data', models.JSONField(blank=True, help_text='Dados SHAP para gráfico Plotly.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='Arquivo CSV com o resultado.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
