# Generated by Django 6.0.4 on 2026-07-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_managedfile_ai_interpretation_and_more'),
        ('pipeline_custo_internacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custointernacaotaskstatus',
            name='output_file',
            field=models.ForeignKey(blank=True, help_text='CSV com os dados da previsão de custo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custo_internacao_tasks', to='api.managedfile'),
        ),
        migrations.AlterField(
            model_name='custointernacaotaskstatus',
            name='output_image_file',
            field=models.ForeignKey(blank=True, help_text='Imagem com a explicação SHAP do custo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custo_internacao_images', to='api.managedfile'),
        ),
    ]
