# Generated by Django 6.0.4 on 2026-07-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_los_hibrido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loshibridotaskstatus',
            options={},
        ),
    ]
