# Generated by Django 5.2.4 on 2025-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_managedfile_file_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file_type',
            field=models.CharField(choices=[('INDICATORS', 'Indicadores de Saúde'), ('K_MEANS', 'K-means de Perfis de Saúde'), ('ARCHETYPE', 'Definição de Arquétipo'), ('PREDICTION', 'Previsão de Internações'), ('LOGISTIC_REGRESSION', 'Regressão Logística'), ('OTHER', 'Outro')], default='INDICATORS', help_text='Classificação do conteúdo do arquivo CSV para visualização.', max_length=25),
        ),
    ]
