# Generated by Django 5.2.4 on 2025-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_managedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='task_id',
            field=models.UUIDField(blank=True, help_text='ID da tarefa Celery que gerou este arquivo.', null=True),
        ),
    ]
