# Generated by Django 5.2.8 on 2026-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_managedfile_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='ai_interpretation',
            field=models.TextField(blank=True, help_text='Análise gerada por LLM', null=True),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='hmm_history',
            field=models.JSONField(blank=True, help_text='Estados Ocultos de Markov', null=True),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='outbreak_alert',
            field=models.BooleanField(default=False, help_text='Alerta de surto estatístico'),
        ),
        migrations.AddField(
            model_name='managedfile',
            name='ruptures',
            field=models.JSONField(blank=True, help_text='Datas de ruptura detectadas', null=True),
        ),
    ]
