# Generated by Django 5.2.8 on 2026-03-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_managedfile_ai_interpretation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='outbreak_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
