# Generated by Django 6.0.4 on 2026-07-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_managedfile_outbreak_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedfile',
            name='ai_interpretation',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='hmm_history',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='outbreak_alert',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='ruptures',
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file_type',
            field=models.CharField(choices=[('INDICATORS', 'Indicadores de Saúde'), ('K_MEANS', 'K-means de Perfis de Saúde'), ('ARCHETYPE', 'Definição de Arquétipo'), ('PREDICTION', 'Previsão de Internações'), ('PATIENT_FLOW', 'Fluxo de Pacientes'), ('RISK_PREDICTION', 'Previsão de Risco (Individual)'), ('LOGISTIC_REGRESSION', 'Regressão Logística'), ('COST_PREDICTION', 'Previsão de Custo'), ('OTHER', 'Outro')], default='INDICATORS', help_text='Classificação do conteúdo do arquivo CSV para visualização.', max_length=25),
        ),
    ]
