# Generated by Django 6.0.4 on 2026-07-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_output_file_and_shap_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='file_type',
            field=models.CharField(choices=[('INDICATORS', 'Indicadores de Saúde'), ('K_MEANS', 'K-means de Perfis de Saúde'), ('ARCHETYPE', 'Definição de Arquétipo'), ('PREDICTION', 'Previsão de Internações'), ('PATIENT_FLOW', 'Fluxo de Pacientes'), ('RISK_PREDICTION', 'Previsão de Risco (Individual)'), ('LOGISTIC_REGRESSION', 'Regressão Logística'), ('COST_PREDICTION', 'Previsão de Custo'), ('DETECCAO_SURTOS', 'Detecção de Surtos'), ('CHART_DATA', 'Dados Internos de Gráfico'), ('LOS_HIBRIDO', 'LOS Híbrido'), ('RISK_PRENATAL', 'Risco Perinatal'), ('INFANT_SURVIVAL', 'Sobrevida Infantil'), ('COX_READMISSION', 'Cox Readmissão'), ('DOENCAS_CRONICAS', 'Doenças Crônicas'), ('OTHER', 'Outro')], default='INDICATORS', help_text='Classificação do conteúdo do arquivo CSV para visualização.', max_length=25),
        ),
    ]
