# Generated by Django 6.0.4 on 2026-07-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_managedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedfile',
            name='file_type',
            field=models.CharField(choices=[('INDICATORS', 'Indicadores de Saúde'), ('K_MEANS', 'K-means de Perfis de Saúde'), ('ARCHETYPE', 'Definição de Arquétipo'), ('PREDICTION', 'Previsão de Internações'), ('PATIENT_FLOW', 'Fluxo de Pacientes'), ('RISK_PREDICTION', 'Previsão de Risco (Individual)'), ('LOGISTIC_REGRESSION', 'Regressão Logística'), ('COST_PREDICTION', 'Previsão de Custo'), ('DETECCAO_SURTOS', 'Detecção de Surtos'), ('CHART_DATA', 'Dados Internos de Gráfico'), ('LOS_HIBRIDO', 'LOS Híbrido'), ('RISK_PRENATAL', 'Risco Perinatal'), ('INFANT_SURVIVAL', 'Sobrevida Infantil'), ('COX_READMISSION', 'Cox Readmissão'), ('DOENCAS_CRONICAS', 'Doenças Crônicas'), ('HOSPITALIZACAO_RDF', 'Hospitalização (BPHO/RDF)'), ('POPULATION_SPACE', 'PopulationSpace (BioSpace)'), ('POP_COMPARE', 'PopulationSpace: Comparação'), ('POP_CAUSAL', 'PopulationSpace: Análise Causal'), ('POP_ANOMALY', 'PopulationSpace: Anomalias'), ('POP_RISK', 'PopulationSpace: Score de Risco'), ('POP_UNCERTAINTY', 'PopulationSpace: Previsão com Incerteza'), ('POP_CLASSIFY', 'PopulationSpace: Classificador'), ('POP_TRANSITIONS', 'PopulationSpace: Transições de Fenótipo'), ('POP_SURVIVAL', 'PopulationSpace: Sobrevida (Fenótipo)'), ('POP_INTERVENE', 'PopulationSpace: Intervenção (Contrafactual)'), ('POP_GRAPH', 'PopulationSpace: Grafo de Similaridade'), ('POP_FACTOR', 'PopulationSpace: Fatores Latentes'), ('POP_TOPOLOGY', 'PopulationSpace: Topologia'), ('POP_EARLY_WARNING', 'PopulationSpace: Alerta Precoce'), ('POP_GNN', 'PopulationSpace: GNN (Classificação de Nós)'), ('POP_DYNAMICS', 'PopulationSpace: Dinâmica & Estabilidade'), ('OTHER', 'Outro')], default='INDICATORS', help_text='Classificação do conteúdo do arquivo CSV para visualização.', max_length=25),
        ),
    ]
