# Generated by Django 5.2.4 on 2025-07-26 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegressaoObitosTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], default='PENDING', max_length=20)),
                ('ufs', models.JSONField(default=list, help_text='Lista de UFs usadas para a análise.')),
                ('anos', models.JSONField(default=list, help_text='Anos de dados históricos usados.')),
                ('diagnostico_cids', models.JSONField(default=list, help_text='Lista de CIDs para o diagnóstico principal.')),
                ('comorbidade_cids', models.JSONField(blank=True, default=list, help_text='(Opcional) Lista de CIDs para a comorbidade.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='Resumo dos resultados, como AUC e coeficientes.', null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='Arquivo CSV de saída com as predições de risco.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regressao_obitos_output_tasks', to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
