# Generated by Django 5.2.4 on 2025-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_regressao_obitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressaoobitostaskstatus',
            name='decision_threshold',
            field=models.FloatField(default=0.5, help_text='Limiar de probabilidade para classificar como óbito.'),
        ),
    ]
