# Generated by Django 6.0.4 on 2026-07-14 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoencasCronicasTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('uf', models.CharField(help_text='UF analisada.', max_length=2)),
                ('cid_doenca', models.CharField(default='I50', help_text='CID-10 da doença crônica analisada.', max_length=10)),
                ('ano_snapshot', models.IntegerField(help_text='Ano de referência para a previsão de hospitalização.')),
                ('n_pacientes_coorte', models.IntegerField(blank=True, help_text='Nº de pacientes na coorte pontuada.', null=True)),
                ('roc_auc', models.FloatField(blank=True, help_text='AUC do modelo no conjunto de teste.', null=True)),
                ('shap_data', models.JSONField(blank=True, help_text='Importância global de features para gráfico Plotly.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='Arquivo CSV com a coorte pontuada.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
