# Generated by Django 5.2.4 on 2025-07-21 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeansTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha'), ('REVOKED', 'Revogada')], default='PENDING', max_length=20)),
                ('n_clusters', models.IntegerField(default=3, help_text='Número de clusters (k).')),
                ('features_for_clustering', models.JSONField(default=list, help_text='Lista de indicadores usados para agrupamento.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('input_file', models.ForeignKey(blank=True, help_text='Arquivo CSV de indicadores de entrada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kmeans_input_tasks', to='api.managedfile')),
                ('output_file', models.ForeignKey(blank=True, help_text='Arquivo CSV de saída com rótulos de cluster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kmeans_output_tasks', to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
