# Generated by Django 6.0.4 on 2026-07-16 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0016_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalizacaoRDFTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], default='PENDING', max_length=20)),
                ('uf', models.CharField(help_text='UF da competência do SIH a carregar/consultar.', max_length=2)),
                ('ano', models.IntegerField(help_text='Ano da competência (ex.: 2025).')),
                ('mes', models.IntegerField(help_text='Mês da competência (1-12).')),
                ('grupo', models.CharField(default='RD', help_text='Grupo de arquivo do SIH (RD/RJ/ER).', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='Totais e contagem por AIHRecordStatus, vindos da consulta SPARQL.', null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='CSV com o agregado de Hospitalization por HealthFacility, via SPARQL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizacao_rdf_output_tasks', to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
