# Generated by Django 6.0.4 on 2026-07-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_output_file_and_shap_data'),
        ('pipeline_risco_readmissao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmissaotaskstatus',
            name='output_file',
            field=models.ForeignKey(blank=True, help_text='Arquivo CSV com o resultado da previsão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readmissao_output_files', to='api.managedfile'),
        ),
        migrations.AddField(
            model_name='readmissaotaskstatus',
            name='shap_data',
            field=models.JSONField(blank=True, help_text='Dados SHAP ou Cox para gráfico Plotly.', null=True),
        ),
    ]
