# Generated by Django 5.2.4 on 2025-07-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_fluxo_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxopacientestaskstatus',
            name='diagnostico_nome',
        ),
        migrations.AlterField(
            model_name='fluxopacientestaskstatus',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
