# Generated by Django 5.2.8 on 2026-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_fluxo_pacientes', '0002_remove_fluxopacientestaskstatus_diagnostico_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxopacientestaskstatus',
            name='ai_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxopacientestaskstatus',
            name='regime_detectado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fluxopacientestaskstatus',
            name='resilience_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
