# Generated by Django 5.2.8 on 2026-03-20 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_fluxo_pacientes', '0003_fluxopacientestaskstatus_ai_interpretation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxopacientestaskstatus',
            name='ai_interpretation',
        ),
        migrations.RemoveField(
            model_name='fluxopacientestaskstatus',
            name='regime_detectado',
        ),
        migrations.RemoveField(
            model_name='fluxopacientestaskstatus',
            name='resilience_score',
        ),
    ]
