"""
Django settings for backend_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent  # Isto resulta em /home/lucas/cognisaude/

DATA_DIR = PROJECT_ROOT / "dados"
REFERENCIA_DIR = PROJECT_ROOT / "referencia"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=y5tmsgrh066gg*%3)7w5xw9+#(%rink_164$$hjzz8viz=r0_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py

# 1. Certifique-se de que 'corsheaders' está no topo do INSTALLED_APPS
# 2. Certifique-se de que 'corsheaders.middleware.CorsMiddleware' é o primeiro em MIDDLEWARE

CORS_ALLOW_ALL_ORIGINS = True  # Libera geral para teste
CORS_ALLOW_CREDENTIALS = True

# Isso é vital: diz ao Django para aceitar e responder ao Preflight (OPTIONS)
from corsheaders.defaults import default_methods, default_headers

CORS_ALLOW_METHODS = list(default_methods) + [
    'OPTIONS',
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'ngrok-skip-browser-warning',
    'x-csrftoken',
]

# settings.py

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'labsus-api.ngrok-free.app', # Seu backend no ngrok
    '.ngrok-free.app',           # Permite qualquer túnel do ngrok
]

# Se você usa CORS
CORS_ALLOWED_ORIGINS = [
    "https://labsus.ngrok-free.app", # Seu frontend no ngrok
    "http://localhost:3000",
    "http://localhost:5173",  # Frontend local
    "http://localhost:3002",  # Frontend live, dev local
    "http://localhost:3005",  # Teste local isolado da integração BPHO
]
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_BACKEND = 'redis://localhost:6379/0' # Geralmente o mesmo do broker
CELERY_CACHE_BACKEND = 'default'
# Application definition
ACCOUNT_MFA_ENABLED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_EMAIL_REQUIRED = True
# backend_project/settings.py
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://labsus.ngrok-free.app", # URL do seu React
    "http://localhost:3002",  # Frontend live, dev local
    "http://localhost:3005",  # Teste local isolado da integração BPHO
]

# settings.py

CSRF_TRUSTED_ORIGINS = [
    'https://labsus-api.ngrok-free.app',
    'https://labsus.ngrok-free.app',
    'http://127.0.0.1:8000',
]

# Essas linhas também são essenciais para túneis HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Permitir o header do Ngrok para pular o aviso
# settings.py

# 1. Garanta que o header do ngrok é permitido pelo Django
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning', # ESSA LINHA É OBRIGATÓRIA
]

# 2. Como você está em túnel, mude para True para testar
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# --- CONFIGURAÇÕES DE HTTPS (PROXY NGROK) ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = False  # Desabilita a segurança de cookies CSRF
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'

CORS_ALLOW_CREDENTIALS = True
## PARA DEBUG
CORS_ALLOW_ALL_ORIGINS = True


ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # Permite login com username OU email

# ... (resto das suas configurações) ...

# Adicione esta nova secção de configuração
REST_AUTH = {
    'REGISTER_SERIALIZER': 'api.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'api.serializers.CustomUserDetailsSerializer',
}

# backend_project/settings.py

# ... (resto das suas configurações) ...

# Adicione esta linha para o desenvolvimento
# Em vez de enviar emails, o Django irá imprimi-los na consola onde o runserver está a ser executado.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# backend_project/settings.py


INSTALLED_APPS = [
    'lexlab_labsus_integration',

    'juridico_app',
    'juridico',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # Adicione aqui
    'django_filters', # <-- ADICIONE ESTA LINHA
    # ... apps existentes ...
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # Garanta que esta linha existe
    'dj_rest_auth.registration',

    # Adicione o provider do Google
    'allauth.socialaccount.providers.google',
    # Nossas Apps
    'api.apps.ApiConfig',
    'api.pipeline_indicadores',
    'api.pipeline_kmeans', # Adicione esta linha
    'api.pipeline_predicao_internacoes', # Adicione esta linha
    'api.pipeline_regressao_obitos',
    'api.pipeline_fluxo_pacientes',
    'api.pipeline_risco_readmissao',
    'api.pipeline_custo_internacao',
    'api.pipeline_deteccao_surtos',
    'api.pipeline_los_hibrido',
    'api.pipeline_risco_perinatal',
    'api.pipeline_sobrevida_infantil',
    'api.pipeline_doencas_cronicas',
    'api.pipeline_ontologia',
    'api.pipeline_hospitalizacao_rdf',
    'api.pipeline_population_space',
    'api.pipeline_cnes_validity',
    'api.pipeline_registros_vitais',
    'api.pipeline_sinan_vigilancia',
    'api.pipeline_fluxo_partos',
    'api.pipeline_previsao_obitos',
    'api.pipeline_previsao_nascimentos',
    'api.pipeline_previsao_producao_ambulatorial',
    'api.pipeline_indices_compostos',
    'api.pipeline_fluxo_alta_complexidade',
    'api.pipeline_difusao_espacial_surto',
    'api.pipeline_desertos_assistenciais',
    'api.pipeline_moran_mortalidade',
    'api.pipeline_lisa_sinan',
    'api.pipeline_hotspots_internacao',
    'api.pipeline_moran_bivariado',
    'api.pipeline_painel_geografico',
    'api.pipeline_bayes_pequenas_areas',
    'api.pipeline_changepoint_bayesiano',
    'api.pipeline_binomial_negativa',
    'api.pipeline_stl_sarima_arboviroses',
    'api.pipeline_quebra_estrutural',
    'api.pipeline_excesso_mortalidade',
    'api.pipeline_sobrevida_tb',
    'api.pipeline_sobrevida_permanencia',
    'api.pipeline_sobrevida_reincidencia',
    'api.pipeline_rede_comorbidades',
    'api.pipeline_rede_especializacao',
    'api.pipeline_diff_in_diff',
    'api.pipeline_rdd_peso_nascer',
    'api.pipeline_gravidade_texto',
    'api.pipeline_similaridade_relatos',
    'api.pipeline_isolation_forest',
    'api.pipeline_hdbscan_estabelecimentos',
    'api.pipeline_umap_perfis',
    'api.pipeline_analise_fatorial',
    'api.pipeline_obito_materno',
    'api.pipeline_sifilis_congenita',
    'api.pipeline_obito_neonatal',
    'api.pipeline_uti_neonatal',
    'api.pipeline_robson',
    'api.pipeline_kotelchuck',
    'api.pipeline_abandono_hanseniase',
    # Apps de Terceiros
    'rest_framework',
    'rest_framework.authtoken', # Para autenticação por token
    'dj_rest_auth',


]

# Adicione esta linha no final do ficheiro. É um requisito do django-allauth.
SITE_ID = 1

# Diga ao DRF para usar autenticação por token por defeito nas suas views
# backend_project/settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Diga ao DRF para usar autenticação por Token como o método padrão
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Opcional, mas uma boa configuração padrão:
        # Por defeito, exige que o utilizador esteja autenticado para aceder a qualquer endpoint.
        'rest_framework.permissions.IsAuthenticated',
    ]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/'
MEDIA_ROOT = BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # Adicione aqui
    'django_filters', # <-- ADICIONE ESTA LINHA
    # ... apps existentes ...
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # Garanta que esta linha existe
    'dj_rest_auth.registration',

    # Adicione o provider do Google
    'allauth.socialaccount.providers.google',
    # Nossas Apps
    'api.apps.ApiConfig',
    'api.pipeline_indicadores',
    'api.pipeline_kmeans', # Adicione esta linha
    'api.pipeline_predicao_internacoes', # Adicione esta linha
    'api.pipeline_regressao_obitos',
    'api.pipeline_fluxo_pacientes',
    'api.pipeline_risco_readmissao',
    'api.pipeline_custo_internacao',
    'api.pipeline_deteccao_surtos',
    'api.pipeline_los_hibrido',
    'api.pipeline_risco_perinatal',
    'api.pipeline_sobrevida_infantil',
    'api.pipeline_doencas_cronicas',
    'api.pipeline_ontologia',
    'api.pipeline_hospitalizacao_rdf',
    'api.pipeline_population_space',
    'api.pipeline_cnes_validity',
    'api.pipeline_registros_vitais',
    'api.pipeline_sinan_vigilancia',
    'api.pipeline_fluxo_partos',
    'api.pipeline_previsao_obitos',
    'api.pipeline_previsao_nascimentos',
    'api.pipeline_previsao_producao_ambulatorial',
    'api.pipeline_indices_compostos',
    'api.pipeline_fluxo_alta_complexidade',
    'api.pipeline_difusao_espacial_surto',
    'api.pipeline_desertos_assistenciais',
    'api.pipeline_moran_mortalidade',
    'api.pipeline_lisa_sinan',
    'api.pipeline_hotspots_internacao',
    'api.pipeline_moran_bivariado',
    'api.pipeline_painel_geografico',
    'api.pipeline_bayes_pequenas_areas',
    'api.pipeline_changepoint_bayesiano',
    'api.pipeline_binomial_negativa',
    'api.pipeline_stl_sarima_arboviroses',
    'api.pipeline_quebra_estrutural',
    'api.pipeline_excesso_mortalidade',
    'api.pipeline_sobrevida_tb',
    'api.pipeline_sobrevida_permanencia',
    'api.pipeline_sobrevida_reincidencia',
    'api.pipeline_rede_comorbidades',
    'api.pipeline_rede_especializacao',
    'api.pipeline_diff_in_diff',
    'api.pipeline_rdd_peso_nascer',
    'api.pipeline_gravidade_texto',
    'api.pipeline_similaridade_relatos',
    'api.pipeline_isolation_forest',
    'api.pipeline_hdbscan_estabelecimentos',
    'api.pipeline_umap_perfis',
    'api.pipeline_analise_fatorial',
    'api.pipeline_obito_materno',
    'api.pipeline_sifilis_congenita',
    'api.pipeline_obito_neonatal',
    'api.pipeline_uti_neonatal',
    'api.pipeline_robson',
    'api.pipeline_kotelchuck',
    'api.pipeline_abandono_hanseniase',
    # Apps de Terceiros
    'rest_framework',
    'dj_rest_auth',
    'rest_framework.authtoken',  # Adicione a aplicação de autenticação do DRF
]

# Para configurar a autenticação via Token:
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# === CORS / CSRF / Cookies para ngrok ===
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok(-free)?\.app$",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok.app",
    "https://*.ngrok-free.app",
    "http://localhost:3002",  # Frontend live, dev local
    "http://localhost:3005",  # Teste local isolado da integração BPHO
]

CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# === BPHO (Brazilian Public Health Ontology) — integração com a ontologia ===
# Endpoint SPARQL somente-leitura servido por owl/sparql_endpoint.py, rodando
# separadamente (ambiente/venv próprio da ontologia, não o venv do LabSUS).
# Precisa estar de pé para qualquer view em api.pipeline_ontologia funcionar.
BPHO_SPARQL_URL = "http://127.0.0.1:8890/sparql"
BPHO_ONTO_DIR = "/home/ld/ontology-datasus/owl"
BPHO_ONTO_PYTHON = "/home/ld/ontology-datasus/owl/.venv/bin/python3"

# Chat em linguagem natural sobre a BPHO via LLM local (Ollama) -- sem API externa.
# qwen3-coder:30b (não llama3.1:8b) porque só ele encadeia corretamente consultas de
# múltiplas etapas (ex.: achar o estabelecimento com mais Hospitalization e então
# checar Affiliation nesse mesmo IRI) -- o llama3.1:8b tentava as duas consultas
# num só tool-call (sintaxe inválida) e desistia. Mais lento (~75s vs ~2-9s), mas
# é o que prova o cruzamento entre sistemas administrativos, que é o ponto real da BPHO.
OLLAMA_URL = "http://localhost:11434"
OLLAMA_MODEL = "qwen3-coder:30b"

# PopulationSpace (biospace/plugins/population/) -- venv próprio (sklearn, networkx),
# igual à ponte já usada para owl/store.py: shell para o Python do biospace via subprocess.
BIOSPACE_DIR = "/home/ld/ontology-datasus/biospace"
BIOSPACE_PYTHON = "/home/ld/ontology-datasus/biospace/venv/bin/python3"
