# Generated by Django 6.0.4 on 2026-07-17 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationSpaceTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], default='PENDING', max_length=20)),
                ('facility_specs', models.JSONField(default=list, help_text='Lista de {facility_uri, ano, mes, uf} carregados nesta execução.')),
                ('k', models.IntegerField(default=3, help_text='Número de clusters (KMeans) usado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='Saída completa do population_cli.py cluster (JSON).', null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='CSV com indicadores + cluster de fenótipo por estabelecimento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='population_space_output_tasks', to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
