# Generated by Django 6.0.4 on 2026-07-13 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0011_remove_managedfile_ai_interpretation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccaoSurtosTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('ufs', models.JSONField(help_text='Lista de UFs analisadas.')),
                ('anos', models.JSONField(help_text='Anos históricos usados.')),
                ('agravo', models.CharField(help_text='Código do agravo (DENG, CHIK, etc).', max_length=10)),
                ('total_alertas', models.IntegerField(default=0, help_text='Total de semanas/municípios em surto.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='CSV com o relatório de alertas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
