# Generated by Django 6.0.4 on 2026-07-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_detecao_surtos_filetype'),
        ('pipeline_deteccao_surtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deteccaosurtostaskstatus',
            name='chart_data_file',
            field=models.ForeignKey(blank=True, help_text='CSV com série temporal completa por município para gráficos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_data_tasks', to='api.managedfile'),
        ),
    ]
