# Generated by Django 5.2.4 on 2025-07-22 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_alter_managedfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionTaskStatus',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciada'), ('PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha'), ('REVOKED', 'Revogada')], default='PENDING', max_length=20)),
                ('ufs', models.JSONField(default=list, help_text='Lista de UFs usadas para a predição.')),
                ('anos_historico', models.JSONField(default=list, help_text='Anos de dados históricos usados para o treinamento.')),
                ('cid_codes', models.JSONField(default=list, help_text='Lista de códigos CID-10 usados para a predição.')),
                ('meses_previsao', models.IntegerField(default=6, help_text='Número de meses previstos no futuro.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('output_file', models.ForeignKey(blank=True, help_text='Arquivo CSV de saída com os resultados da previsão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_output_tasks', to='api.managedfile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
