# Generated by Django 5.2.8 on 2026-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_predicao_internacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='lyapunov_exp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='potential_centers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='potential_u',
            field=models.JSONField(blank=True, help_text='Curva do Poço de Potencial', null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='regime_detectado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='resilience_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
