# Generated by Django 5.2.8 on 2026-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_predicao_internacoes', '0002_predictiontaskstatus_lyapunov_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='coherence_history',
            field=models.JSONField(blank=True, help_text='Série de Coerência (I)', null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='energy_history',
            field=models.JSONField(blank=True, help_text='Série de Energia (Phi)', null=True),
        ),
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='entropy_history',
            field=models.JSONField(blank=True, help_text='Série de Entropia (H)', null=True),
        ),
    ]
