# Generated by Django 5.2.8 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_predicao_internacoes', '0003_predictiontaskstatus_coherence_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiontaskstatus',
            name='atlas_data',
            field=models.JSONField(blank=True, help_text='Lista de indicadores MetastableX por município', null=True),
        ),
    ]
