# Generated by Django 6.0.4 on 2026-07-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_predicao_internacoes', '0004_predictiontaskstatus_atlas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='atlas_data',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='coherence_history',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='energy_history',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='entropy_history',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='lyapunov_exp',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='potential_centers',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='potential_u',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='regime_detectado',
        ),
        migrations.RemoveField(
            model_name='predictiontaskstatus',
            name='resilience_score',
        ),
    ]
